### ISSUE TITLE
nano?

### ISSUE THREAD

**Issue by PatrickSkovgaard** [trinib/Linux-Bash-Commands#3]
In the command list, how come **nano** is not present?
I see that it is used further below, but only one time is it present throughout. 
Should it be added under the _N_ section of commands? I was expecting it at least. And since **nc** (_netcat_) which is not a default command line option is there, i definitely think _nano_ should be there as well, since it usually is (might be some cases where it's not present, but I have never seen it myself).

**Comment by trinib** [comment]
will add it in 👍
